### ISSUE TITLE
Doesn't work with service outages.

### ISSUE THREAD

**Issue by The-Synthax** [nicoco007/LoL-Auto-Login#22]
There is a current service outage announcement in the client due to Clash being canceled.

> 0:00:00:00.0029991 [INFO] Started LoL Auto Login v2.0.2.0
> 0:00:00:00.0199940 [INFO] Loading settings from "D:\Riot Games\League of 
 > Legends\Config\LoLAutoLoginSettings.yaml"
> 0:00:00:00.0949740 [INFO] Loaded settings.
> 0:00:00:00.1839470 [INFO] Client is not running, launching client.
> 0:00:00:00.1839470 [INFO] Waiting for 30000 ms.
> 0:00:00:01.0326904 [INFO] Found new/resized window: {Handle=1182906, Name="League of Legends",  Class="RCLIENT", Rectangle={X=0,Y=0,Width=1280,Height=720}}
> 0:00:00:01.0326904 [INFO] Client found after 783 ms!
> 0:00:00:02.6182458 [INFO] Found new/resized window: {Handle=1182906, Name="League of Legends",  Class="RCLIENT", Rectangle={X=320,Y=165,Width=1280,Height=720}}
> 0:00:00:06.2908305 [INFO] Password box found after 6041 ms!
> 0:00:00:06.2978287 [INFO] Entering password...
> 0:00:00:06.3307295 [INFO] Successfully entered password (well, hopefully)!
> 0:00:00:06.3677175 [INFO] Deleting 1 old log files...
> 0:00:00:06.3727158 [INFO] Done.
> 0:00:00:06.3747154 [INFO] Pixel matching statistics:
> 0:00:00:06.3747154 [INFO]   Minimum: 0.06934 (71/1024)
> 0:00:00:06.3757157 [INFO]   Maximum: 0.89355 (915/1024)
> 0:00:00:06.3757157 [INFO]   Required: 0.85000 (870/1024)
> 0:00:00:06.3757157 [INFO] Shutting down

**Comment by nicoco007** [comment]
Hm. That's annoying. I'll see what I can do.

**Comment by nicoco007** [comment]
I was going to ask you to try out [this version](https://ci.gnyra.com/job/LoL-Auto-Login/job/master/54/artifact/LoLAutoLogin-master-54.zip) but it looks like they got rid of the warning. This should work in the future though (but I wouldn't recommend using this version since it might not be perfectly stable).

I'll close this issue for now. If you get the same problem at some point in the future, feel free to open another one.
